# Generated by Django 6.0.1 on 2026-02-11 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_review_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comment',
        ),
    ]
