# Generated by Django 6.0.1 on 2026-02-14 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_review_date_review_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
