# Generated by Django 6.0.1 on 2026-02-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Not Paid', 'Not Paid'), ('Shipped', 'Shipped'), ('Deliverd', 'Deliverd')], default='Pending', max_length=200),
        ),
    ]
