# Generated by Django 6.0.1 on 2026-02-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='Total_price',
        ),
    ]
