# Generated by Django 6.0.1 on 2026-02-13 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderitem_price_alter_orderitem_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Total_price',
            new_name='total_price',
        ),
    ]
