# Generated by Django 6.0.1 on 2026-02-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_rename_total_price_orderitem_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Not Paid', 'Not Paid'), ('Ready To Ship', 'Ready To Ship'), ('Shipped', 'Shipped'), ('Deliverd', 'Deliverd'), ('Canceled', 'Canceled')], default='Pending', max_length=200),
        ),
    ]
